
const {
  VITE_DEV_SERVER_URL,
  VITE_DEV_SERVER_PORT,
  VITE_DEV_SERVER_CLIENT_PORT,
  VITE_PREFIX,
  VITE_TITLE,
  VITE_API_BASE_URL,
  VITE_LOCALE,
  VITE_API_ACCESS_KEY,

  VITE_MAPBOX_STYLE_TAKESHIBA,
  VITE_MAPBOX_ACCESS_TOKEN,
  VITE_MAPBOX_LONG,
  VITE_MAPBOX_LAT,
  VITE_GOOGLE_ANALSTIC_ID,
  VITE_APPLICATION_INSIGHT_CONNECTION_STRING
} = import.meta.env;

export default class ENV {
  static get APP_PREFIX() { return VITE_PREFIX || 'sb' };
  static get APP_TITLE() { return VITE_TITLE || '防災' };
  static get APP_LOCALE() { return VITE_LOCALE || 'ja' };
  static get APP_API_URL() { return VITE_API_BASE_URL };
  static get APP_API_ACESS_KEY() { return VITE_API_ACCESS_KEY };
  static get DEV_SERVER_URL() { return VITE_DEV_SERVER_URL };
  static get DEV_SERVER_PORT() { return VITE_DEV_SERVER_PORT };
  static get DEV_SERVER_CLIENT_PORT() { return VITE_DEV_SERVER_CLIENT_PORT };

  static get MAPBOX_STYLE_TAKESHIBA() {return VITE_MAPBOX_STYLE_TAKESHIBA};
  static get MAPBOX_ACCESS_TOKEN() {return VITE_MAPBOX_ACCESS_TOKEN};
  static get MAPBOX_LONG() {return VITE_MAPBOX_LONG};
  static get MAPBOX_LAT() {return VITE_MAPBOX_LAT};

  static get GOOGLE_ANALSTIC_ID() { return VITE_GOOGLE_ANALSTIC_ID };
  static get APPLICATION_INSIGHT_CONNECTION_STRING() { return VITE_APPLICATION_INSIGHT_CONNECTION_STRING };
}